module.exports = {
    name: 'quote',
    description: 'Returns a random quote of a character specified by user.',
    execute(message, args) {
      if (args == "neptune") {
          const neptune = ["Wow, you have 'Nep' in your name, too?! Crazy! This Nep can't help but feel some sort of sentimental fate at play here!", "V for Victory!", "Ooooh! Even in your normal form, you're pretty cool-looking!", "If I ever had a younger sister, she might even look like you! Aw, what a pretty thought. I'd love to have a younger sister someday.", "It's a bad move, Uzume. Anyway, I've decided to put this gross bug into my specimen book, so you can't!", "Last but not least, I just tape her down and...Voila! Finished!", "Yippeee! I've been kinda bummed out since I got here. It's been super lonely without anyone around.", "Oooh, so there's another me out there. I'd like to meet her!", "That's right. From what I can tell, the world you're from and my world are different, too.", "Uh-huh! Hmm, I think she was a CPU named Plu-something?", "Although, I've spent more time travelling through different dimensions than at home, so I've never even met her or seen her.", "Oooh...Such a new feeling...", "No way! Baths are the best when everyone takes them together! That's the trope!", "I'll have to write about this later in my Nep-Note.", "The Nep-Note is a notebook too, you know? It's a convenient notebook that I write in along with being a specimen book.", "Also, if something I put in the book has a special ability, I can draw out a part of that power and use it freely.", "W-What is this food?! it's beyond disgusting! In fact, I'd say it's borderline dangerous!", "Ooooh! It's the other me! She's so tiny!", "Wowee, wow! My small self is so cute!", "Hey there, miss! You have super amazing style, what's your secret?", "Ooh. Hey, would it be okay if I touched your chest? It's so big, I'm kinda curious.", "You guys are plenty strong, as well! Seriously, I said it already, but you're much stronger than last time, Nepgear.", "You can't be more popular than me. I'm the main character of this franchise and stuff!", "I think I've got a little more spring in my step or whatever, but not much.", "'Kay, I'm gonna go stir up some crazy trouble, but once everything gets back to normal-bormal, let's relax with Nep Jr.", "Actually, I heard this game is supposed to come with some cool bonus items.", "Et tu, Compa?! Blah, fine! You're both big dumburgers!", "I'm gonna use my CPU authority to get a life-size figure of me manufactured. My boobies'll increase by 20 percent!", "nepgear needs to get me my cookies lol", "Listen up, my amazing little sister. I came up with an awesome strategy. We can totally get all the shares of Planeptune back with this. No, all of Gamindustri's shares!", "Whoa there, kiddo. Don't get shy. All CPUs must be able to sing and dance. It's like a requirement or whatever.", "Most def, my gyrating sibling. Now, for the moment of truth!", "Oh, so you're old enough to ask that. Are you starting to realize the crazy importance of being a CPU and stuff?"]     
          
          let selectedQuote = neptune[Math.floor(Math.random() * neptune.length)];      
          message.channel.send(`${selectedQuote}`, {files: ['https://i.imgur.com/PIJkDAf.png']});   
      } else if (args == "help") {
          message.channel.send("n+quote accepts an argument of a character name from the Neptunia series. Current plans are for the main cast. Names wrapped in brackets are not currently available. n+quote <name> ([Compa], [Iffy], Neptune, [Noire], [Blanc], and [Vert])", {files: ['https://i.imgur.com/P84BV9y.png']});
      } else {
        message.channel.send("Looks like something went wrong. Type n+quote <help> for an explanation of the command.", {files: ['https://i.imgur.com/18DlOoN.png']});
      }
    }
  };